name: Flask API CI/CD Pipeline

on:
  # Trigger the workflow on pushes to the 'main' branch
  push:
    branches:
      - main
  # Allow manual trigger from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Using the Python version specified in your original YAML
          python-version: '3.10' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run unit tests
        # Set environment variables for testing environment if needed
        env:
          DATABASE_URL: sqlite:///test.db
          SECRET_KEY: test_secret_key
        # Using the test command specified in your original YAML
        run: python -m unittest discover tests

  deploy:
    # This job only runs if the build-and-test job completes successfully
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    # CRITICAL: Explicitly ensure deployment only happens on the main branch
    if: github.ref == 'refs/heads/main' 
    
    steps:
      - name: Trigger Render Deployment via API
        # Using the cURL command specified in your original YAML
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            "https://api.render.com/deploy/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
